### ISSUE TITLE
@img-insight is not available in github copilot chat

### ISSUE THREAD

**Issue by vinda-parab** [ambilykk/img-insight-extension#1]
Hi,

Have added the .env file.
Started the extension with npm start.

<img width="308" alt="image" src="https://github.com/user-attachments/assets/32a701e8-9ffc-4a2a-9e57-ac3bfdba61a1">

However, in Coplot chat I am not getting @img-insight option.

<img width="307" alt="image" src="https://github.com/user-attachments/assets/c9b0b6b4-498a-48ee-8550-b3edb9274e52">

Can you pls check and suggest. @ambilykk

**Comment by ambilykk** [comment]
Hello @vinda-parab 

I have modified the README with pre-requisites and [Copilot Extension configuration video](https://github.com/ambilykk/img-insight-extension?tab=readme-ov-file#github-copilot-extension-configuration-video). Please refer the video to setup your first Copilot Extension.

**Comment by vinda-parab** [comment]
Hello @ambilykk 
https://github.com/octodemo/amb-copilot-extensions.git mentioned in the ReadMe is not accessible. Can you please check.

Regards,
Vinda

**Comment by ambilykk** [comment]
Thank you @vinda-parab for reporting the bug; I have fixed the repo URL.
