### ISSUE TITLE
Copilot agent must be hosted on a server that is accessible to the internet.?

### ISSUE THREAD

**Issue by vinda-parab** [ambilykk/img-insight-extension#3]
hi @ambilykk 

Does the Copilot agent must be hosted on a server that is accessible to the internet?

I am referring to :  https://docs.github.com/en/copilot/building-copilot-extensions/creating-a-copilot-extension/configuring-your-server-to-deploy-your-copilot-agent

Note: By following your config video, i have done the setup, but was not able to get the extension in the chat window.
Is it because - i m using Github as an enterprise user and the agent needs to be installed at org/enterprise level?
Have raised a request to org admin - to approve the request for installation, which had led to the question - Does the Copilot agent must be hosted on a server that is accessible to the internet?

**Comment by ambilykk** [comment]
Hello @vinda-parab 

Yes, you need to host the Copilot Extension on a server accessible from the internet. For testing, you can use platforms like Codespaces, Ngrok, or other servers. However, for a permanent setup, it should be hosted as a publicly accessible service.

For testing purpose, you can install/configure the extension for an individual user. When it is ready for Production, you can configure the Extension at Org level.

**Comment by vinda-parab** [comment]
Thank you for your quick reply @ambilykk .
I am at present exploring this extension. Is it possible for me to use this locally on my machine VS Code without having to actually add as an agent on Github?

**Comment by ambilykk** [comment]
You should configure the Extension under Developer Configuration. Please check the [Copilot Extension Configuration Video](https://github.com/ambilykk/img-insight-extension?tab=readme-ov-file#github-copilot-extension-configuration-video)

**Comment by vinda-parab** [comment]
@ambilykk I wanted to know if this extension can be installed locally (on my local IDE) for exploration? at present i don't want to do any Github Agent related configuration in the Github settings. Please confirm. If yes, how to go about this?

**Comment by ambilykk** [comment]
@vinda-parab 
This extension have dependency on GitHub Models or Azure OpenAI Service, which you should provision first. Once you setup the model, you can run the code in local and interact with it using any of the API testing tools like Ngrok, Postman, etc. If you have Ngrok setup locally, you can host the same as well.

**Comment by vinda-parab** [comment]
@ambilykk I have Azure OpenAI service, can you instruct me to how to use the model with Postman?

**Comment by ambilykk** [comment]
@vinda-parab
Local setup instuctions provided in the [README](https://github.com/ambilykk/img-insight-extension?tab=readme-ov-file#local-setup-instructions); please refer the same. 

You can refer the Postman documentation for how to test local api using Postman.
